# Generated by Django 3.0.2 on 2020-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='wedding_party',
        ),
        migrations.AddField(
            model_name='guest',
            name='wedding_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='attire',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='other_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parking',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='transportation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
