# Generated by Django 3.0.2 on 2020-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20200405_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='invitation_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_sent',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_sent',
        ),
        migrations.AddField(
            model_name='party',
            name='first_accessed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='last_accessed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
