# Generated by Django 3.0.2 on 2020-04-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20200405_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='email_verfied',
            field=models.NullBooleanField(default=False),
        ),
    ]
