# Generated by Django 3.0.2 on 2020-04-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_weddingparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingparty',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
