# Generated by Django 3.0.2 on 2020-04-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20200406_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingparty',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
